sudo: false
dist: trusty
language: python
cache: pip
python:
  - "2.7.10"
  - "2.7.13"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip install flake8
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --statistics
  # exit-zero treates all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-line-length=127 --statistics
install:
  - python setup.py install
  - pip install pexpect
script:
  - python kubeshell/tests/test_cli.py
sudo: false
